<?php

if (!defined('STATUS_ACCOUNT_USER_REGISTER')) define('STATUS_ACCOUNT_USER_REGISTER', 0);
if (!defined('STATUS_ACCOUNT_USER_ACTIVE')) define('STATUS_ACCOUNT_USER_ACTIVE', 1);
if (!defined('STATUS_ACCOUNT_USER_NOT_ACTIVE')) define('STATUS_ACCOUNT_USER_NOT_ACTIVE', 2);

if (!defined('STATUS_ACCOUNT_CUSTOMER_REGISTER')) define('STATUS_ACCOUNT_CUSTOMER_REGISTER', 0);
if (!defined('STATUS_ACCOUNT_CUSTOMER_ACTIVE')) define('STATUS_ACCOUNT_CUSTOMER_ACTIVE', 1);
if (!defined('STATUS_ACCOUNT_CUSTOMER_NOT_ACTIVE')) define('STATUS_ACCOUNT_CUSTOMER_NOT_ACTIVE', 2);
